image: crycode/nodejs-dev-env

stages:
  - build
  - deploy

cache:
  paths:
    - node_modules/

node-gyp-build:
  stage: build
  script:
    - npm config set unsafe-perm true
    - npm install
    - node-gyp rebuild

typescript-check:
  stage: build
  script:
    - tsc

publish-to-npm:
  stage: deploy
  script:
    - npm config set unsafe-perm true
    - npm config set //registry.npmjs.org/:_authToken=$NPM_TOKEN
    - npm publish
  environment:
    name: production
    url: https://www.npmjs.com/package/radiohead-serial
  when: manual
  only:
    - tags
